"""tempestweb.components — ready-to-use fields, forms and Material 3 buttons.

Pre-built, validated building blocks so an app declares a field, a button or a
whole form in one line instead of wiring inputs, labels, errors and validators
by hand:

    from tempestweb.components import EmailField, PasswordField, LoginForm
    from tempestweb.components import filled_button, text_button

``EmailField``/``PasswordField`` and ``TextField`` are tempestweb-native, styled
for the Material 3 light surface the base stylesheet renders; the BR fields
(:class:`PhoneField`/:class:`CPFField`/:class:`CNPJField`/:class:`AddressField`)
wrap the core's masked inputs. The ``*_button`` helpers build the MD3 button
variants. Everything renders identically in Mode A (WASM) and Mode B (server).
"""

from __future__ import annotations

from tempestweb.components.buttons import (
    elevated_button,
    filled_button,
    outlined_button,
    text_button,
    tonal_button,
)
from tempestweb.components.fields import (
    AddressField,
    CNPJField,
    CPFField,
    EmailField,
    PasswordField,
    PhoneField,
    TextField,
    validate_cnpj,
    validate_cpf,
    validate_email,
    validate_phone,
)
from tempestweb.components.forms import LoginForm, SignupForm
from tempestweb.components.library import (
    Accordion,
    AddressInput,
    Alert,
    AppBar,
    Avatar,
    Badge,
    Banner,
    BarChart,
    Breadcrumb,
    Burger,
    Calendar,
    Card,
    ChartSeries,
    Chip,
    Clock,
    CNPJInput,
    CollapsingAppBar,
    ConfidenceBadge,
    CPFInput,
    DataTable,
    DetectionBox,
    DetectionOverlay,
    Divider,
    DocumentPicker,
    Drawer,
    EmailInput,
    EmptyState,
    Footer,
    Grid,
    Header,
    HStack,
    ImagePicker,
    ImagePicture,
    LineChart,
    ListTile,
    MetricCard,
    NavBar,
    PasswordInput,
    PhoneInput,
    ProgressStepper,
    RadioGroup,
    Rating,
    ResultView,
    Scaffold,
    SearchBar,
    SegmentedControl,
    Sidebar,
    Stat,
    StatCard,
    Stepper,
    StyledContainer,
    Surface,
    Table,
    TableCell,
    TableRow,
    Tabs,
    Tag,
    VStack,
    confidence_scheme,
)

__all__ = [
    "Accordion",
    "AddressField",
    "AddressInput",
    "Alert",
    "AppBar",
    "Avatar",
    "Badge",
    "Banner",
    "BarChart",
    "Breadcrumb",
    "Burger",
    "CNPJField",
    "CNPJInput",
    "CPFField",
    "CPFInput",
    "Calendar",
    "Card",
    "ChartSeries",
    "Chip",
    "Clock",
    "CollapsingAppBar",
    "ConfidenceBadge",
    "DataTable",
    "DetectionBox",
    "DetectionOverlay",
    "Divider",
    "DocumentPicker",
    "Drawer",
    "EmailField",
    "EmailInput",
    "EmptyState",
    "Footer",
    "Grid",
    "HStack",
    "Header",
    "ImagePicker",
    "ImagePicture",
    "LineChart",
    "ListTile",
    "LoginForm",
    "MetricCard",
    "NavBar",
    "PasswordField",
    "PasswordInput",
    "PhoneField",
    "PhoneInput",
    "ProgressStepper",
    "RadioGroup",
    "Rating",
    "ResultView",
    "Scaffold",
    "SearchBar",
    "SegmentedControl",
    "Sidebar",
    "SignupForm",
    "Stat",
    "StatCard",
    "Stepper",
    "StyledContainer",
    "Surface",
    "Table",
    "TableCell",
    "TableRow",
    "Tabs",
    "Tag",
    "TextField",
    "VStack",
    "confidence_scheme",
    "elevated_button",
    "filled_button",
    "outlined_button",
    "text_button",
    "tonal_button",
    "validate_cnpj",
    "validate_cpf",
    "validate_email",
    "validate_phone",
]
