"""The tempest-core component library, re-exported for tempestweb apps.

tempest-core ships a broad Material 3 component set — layout scaffolds, app bars,
navigation, cards, lists, inputs, feedback, tables and charts. Every component
lowers to the renderer-agnostic primitives (``Column``/``Row``/``Text``/…) or to a
``Canvas`` draw-command list, both of which the web client renders, so the whole
set works unchanged in Mode A (WASM) and Mode B (server).

This module re-exports that library under :mod:`tempestweb.components` so an app
has a single import home for both the tempestweb-native helpers (the ``*_button``
variants, ``EmailField``/``PasswordField``, ``LoginForm``) and the core
components:

    from tempestweb.components import Card, DataTable, BarChart, ChartSeries

The names are re-bound, not re-implemented — each is the very class from
:mod:`tempest_core.components`, so behavior and typing match the core exactly.
The value models and helpers needed to drive the components (``ChartSeries``,
``TableRow``/``TableCell``, ``DetectionBox``, ``confidence_scheme``) come along.
"""

from __future__ import annotations

from tempest_core.components import (
    Accordion,
    AddressInput,
    Alert,
    AppBar,
    Avatar,
    Badge,
    Banner,
    BarChart,
    Breadcrumb,
    Burger,
    Calendar,
    Card,
    ChartSeries,
    Chip,
    Clock,
    CNPJInput,
    CollapsingAppBar,
    ConfidenceBadge,
    CPFInput,
    DataTable,
    DetectionBox,
    DetectionOverlay,
    Divider,
    DocumentPicker,
    EmailInput,
    EmptyState,
    Footer,
    Grid,
    Header,
    HStack,
    ImagePicker,
    ImagePicture,
    LineChart,
    ListTile,
    MetricCard,
    NavBar,
    PasswordInput,
    PhoneInput,
    ProgressStepper,
    RadioGroup,
    Rating,
    ResultView,
    Scaffold,
    SearchBar,
    SegmentedControl,
    Sidebar,
    Stat,
    StatCard,
    Stepper,
    StyledContainer,
    Surface,
    Table,
    TableCell,
    TableRow,
    Tabs,
    Tag,
    VStack,
    confidence_scheme,
)

__all__ = [
    "Accordion",
    "AddressInput",
    "Alert",
    "AppBar",
    "Avatar",
    "Badge",
    "Banner",
    "BarChart",
    "Breadcrumb",
    "Burger",
    "CNPJInput",
    "CPFInput",
    "Calendar",
    "Card",
    "ChartSeries",
    "Chip",
    "Clock",
    "CollapsingAppBar",
    "ConfidenceBadge",
    "DataTable",
    "DetectionBox",
    "DetectionOverlay",
    "Divider",
    "DocumentPicker",
    "EmailInput",
    "EmptyState",
    "Footer",
    "Grid",
    "HStack",
    "Header",
    "ImagePicker",
    "ImagePicture",
    "LineChart",
    "ListTile",
    "MetricCard",
    "NavBar",
    "PasswordInput",
    "PhoneInput",
    "ProgressStepper",
    "RadioGroup",
    "Rating",
    "ResultView",
    "Scaffold",
    "SearchBar",
    "SegmentedControl",
    "Sidebar",
    "Stat",
    "StatCard",
    "Stepper",
    "StyledContainer",
    "Surface",
    "Table",
    "TableCell",
    "TableRow",
    "Tabs",
    "Tag",
    "VStack",
    "confidence_scheme",
]
