"""Scaffold production deploy files for ``tempestweb deploy`` (Track S — S5).

Generates a tailored **nginx** reverse-proxy config (TLS + WebSocket upgrade +
sticky sessions), a ``Dockerfile``, a ``docker-compose.yml`` and a ``DEPLOY.md``
guide into a target directory — so a Mode B (server) app has a correct,
copy-pasteable deployment instead of hand-writing proxy rules.

The nginx config is parameterized from the project's ``tempestweb.toml`` (the
upstream port) plus flags (``server_name``, TLS, replica count).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from tempestweb.cli.config import load_config

__all__ = [
    "DEPLOY_FILES",
    "DeployError",
    "DeployResult",
    "render_deploy_files",
    "scaffold_deploy",
]

#: The files ``tempestweb deploy`` writes, in a stable order.
DEPLOY_FILES: tuple[str, ...] = (
    "nginx.conf",
    "Dockerfile",
    "docker-compose.yml",
    "DEPLOY.md",
)


class DeployError(RuntimeError):
    """Raised when deploy scaffolding cannot proceed."""


@dataclass(slots=True)
class DeployResult:
    """The outcome of scaffolding deploy files.

    Attributes:
        out_dir: The directory the files were written to.
        files: The relative file names written.
    """

    out_dir: Path
    files: tuple[str, ...]


def _nginx_conf(
    *, port: int, server_name: str, tls: bool, replicas: int, sticky: bool = True
) -> str:
    """Render a tailored nginx reverse-proxy config."""
    servers = "\n".join(
        f"    server app{'' if i == 0 else i}:{port};" for i in range(replicas)
    )
    if sticky:
        note = (
            "# `ip_hash` pins each client to one backend — SSE's GET+POST must\n"
            "# land on the same worker (WS is self-contained). Drop it (--no-sticky)\n"
            "# when using a RedisSessionRouter.\n"
        )
        upstream = (
            "# Generated by `tempestweb deploy`. Reverse proxy for a Mode B app.\n"
            "#\n"
            f"{note}"
            f"upstream tempestweb {{\n    ip_hash;\n{servers}\n}}\n"
        )
    else:
        upstream = (
            "# Generated by `tempestweb deploy`. Reverse proxy for a Mode B app.\n"
            "#\n"
            "# No stickiness: WS is self-contained and SSE uses a shared session\n"
            "# backend (RedisSessionRouter). Round-robin across replicas.\n"
            f"upstream tempestweb {{\n{servers}\n}}\n"
        )

    def _proxy_location() -> str:
        return (
            "    location / {\n"
            "        proxy_pass http://tempestweb;\n"
            "        proxy_http_version 1.1;\n\n"
            "        # WebSocket upgrade (GET /ws).\n"
            "        proxy_set_header Upgrade $http_upgrade;\n"
            '        proxy_set_header Connection "upgrade";\n\n'
            "        # Client identity for the origin allowlist + rate limit.\n"
            "        proxy_set_header Host $host;\n"
            "        proxy_set_header Origin $http_origin;\n"
            "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"
            "        proxy_set_header X-Forwarded-Proto $scheme;\n\n"
            "        # WS/SSE are long-lived: keep idle streams, don't buffer.\n"
            "        proxy_read_timeout 3600s;\n"
            "        proxy_send_timeout 3600s;\n"
            "        proxy_buffering off;\n"
            "    }\n"
        )

    health = (
        "    location = /health {\n"
        "        proxy_pass http://tempestweb;\n"
        "        access_log off;\n"
        "    }\n"
    )

    if tls:
        http = (
            "server {\n"
            "    listen 80;\n"
            f"    server_name {server_name};\n"
            "    return 301 https://$host$request_uri;\n"
            "}\n\n"
        )
        https = (
            "server {\n"
            "    listen 443 ssl;\n"
            "    http2 on;\n"
            f"    server_name {server_name};\n\n"
            "    ssl_certificate     /etc/nginx/certs/fullchain.pem;\n"
            "    ssl_certificate_key /etc/nginx/certs/privkey.pem;\n\n"
            f"{_proxy_location()}\n{health}}}\n"
        )
        return upstream + "\n" + http + https

    http = (
        "server {\n"
        "    listen 80;\n"
        f"    server_name {server_name};\n\n"
        f"{_proxy_location()}\n{health}}}\n"
    )
    return upstream + "\n" + http


def _dockerfile(*, port: int) -> str:
    """Render a production Dockerfile for the app."""
    probe = (
        f'python -c "import urllib.request; '
        f"urllib.request.urlopen('http://127.0.0.1:{port}/health')\""
    )
    cmd = (
        f'["tempestweb", "run", "--mode", "server", '
        f'"--host", "0.0.0.0", "--port", "{port}"]'
    )
    return f"""\
# Generated by `tempestweb deploy`. One uvicorn worker per container — scale with
# replicas behind the sticky proxy (see DEPLOY.md), not with --workers.
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app

RUN pip install "tempestweb[server]"
COPY . .

EXPOSE {port}
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD {probe}

CMD {cmd}
"""


def _compose(*, port: int, tls: bool) -> str:
    """Render a docker-compose file wiring the app behind nginx."""
    ports = '      - "80:80"\n      - "443:443"' if tls else '      - "80:80"'
    certs = "\n      # - ./certs:/etc/nginx/certs:ro" if tls else ""
    return f"""\
# Generated by `tempestweb deploy`.
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "{port}"
    environment:
      - TEMPESTWEB_TOKEN=${{TEMPESTWEB_TOKEN:-}}
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      - app
    ports:
{ports}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro{certs}
    restart: unless-stopped
"""


def _deploy_md(*, name: str, port: int, server_name: str, tls: bool) -> str:
    """Render the deploy guide."""
    scheme = "https" if tls else "http"
    host = server_name if server_name != "_" else "localhost"
    origin = server_name if server_name != "_" else "app.example.com"
    proxy_line = "TLS on 443 + HTTP→HTTPS redirect" if tls else "HTTP on 80"
    tls_note = (
        ""
        if tls
        else (
            "\n## TLS\n\nRe-run `tempestweb deploy --tls` and mount your certs "
            "into `/etc/nginx/certs`.\n"
        )
    )
    return f"""\
# Deploy — {name}

Generated by `tempestweb deploy`. A Mode B (server) app behind nginx.

## Quick start

```bash
docker compose up --build
# app at {scheme}://{host}
```

## What's here

- **`Dockerfile`** — installs `tempestweb[server]`, runs the FastAPI host on
  port {port} (one worker), with a `/health` HEALTHCHECK.
- **`nginx.conf`** — reverse proxy: WebSocket upgrade, `X-Forwarded-*`, long
  streaming timeouts, `ip_hash` (sticky), {proxy_line}.
- **`docker-compose.yml`** — `app` + `proxy`.

## Harden the app (required for public exposure)

Pass a `SecurityConfig` to `create_app` — see the
[Security guide](https://mauriciobenjamin700.github.io/tempestweb/en/security/):

```python
create_app(make_state, view, security=SecurityConfig(
    authenticate=jwt_authenticator(os.environ["JWT_KEY"]),
    allowed_origins=["{scheme}://{origin}"],
    max_connections=1000,
    max_connections_per_minute=60,
    security_headers=True,
    hsts={tls},
), metrics=True)
```

## Scale

Session state is **in-process**, so `ip_hash` pins each client to one replica.
Add replicas to the `upstream` block in `nginx.conf` and scale the `app`
service; keep **1 worker per container**. `GET /health` reports readiness;
`GET /metrics` (when `metrics=True`) exposes Prometheus counters.
{tls_note}"""


def render_deploy_files(
    root: str | Path,
    *,
    server_name: str = "_",
    tls: bool = False,
    replicas: int = 1,
    sticky: bool = True,
    port: int | None = None,
) -> dict[str, str]:
    """Render every deploy file's contents without touching disk.

    Args:
        root: The project directory (read for the ``tempestweb.toml`` port/name).
        server_name: The nginx ``server_name`` (default ``_`` = any host).
        tls: When ``True``, emit a 443 TLS server block + HTTP→HTTPS redirect.
        replicas: Number of ``app`` upstream servers to list.
        sticky: Emit ``ip_hash`` (sticky sessions); set ``False`` with a
            ``RedisSessionRouter`` for round-robin SSE scale-out.
        port: Override the app port (defaults to the config's port).

    Returns:
        A mapping of file name to contents covering :data:`DEPLOY_FILES`.

    Raises:
        DeployError: If ``replicas`` is below 1.
    """
    if replicas < 1:
        raise DeployError("replicas must be >= 1")
    config = load_config(root)
    app_port = port if port is not None else config.port
    return {
        "nginx.conf": _nginx_conf(
            port=app_port,
            server_name=server_name,
            tls=tls,
            replicas=replicas,
            sticky=sticky,
        ),
        "Dockerfile": _dockerfile(port=app_port),
        "docker-compose.yml": _compose(port=app_port, tls=tls),
        "DEPLOY.md": _deploy_md(
            name=config.name, port=app_port, server_name=server_name, tls=tls
        ),
    }


def scaffold_deploy(
    root: str | Path,
    *,
    out: str | Path | None = None,
    server_name: str = "_",
    tls: bool = False,
    replicas: int = 1,
    sticky: bool = True,
    force: bool = False,
) -> DeployResult:
    """Write the deploy files into ``out`` (default ``<root>/deploy``).

    Args:
        root: The project directory.
        out: The output directory (default ``<root>/deploy``).
        server_name: The nginx ``server_name``.
        tls: Emit a TLS (443) server block.
        replicas: Upstream ``app`` replica count.
        sticky: Emit ``ip_hash`` (default); ``False`` for round-robin.
        force: Overwrite existing files instead of refusing.

    Returns:
        A :class:`DeployResult`.

    Raises:
        DeployError: If a target file exists and ``force`` is ``False``, or an
            argument is invalid.
    """
    root_path = Path(root).resolve()
    out_dir = Path(out).resolve() if out is not None else (root_path / "deploy")
    contents = render_deploy_files(
        root_path,
        server_name=server_name,
        tls=tls,
        replicas=replicas,
        sticky=sticky,
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in DEPLOY_FILES:
        target = out_dir / name
        if target.exists() and not force:
            raise DeployError(f"{target} already exists (pass force=True to overwrite)")
        target.write_text(contents[name], encoding="utf-8")
    return DeployResult(out_dir=out_dir, files=DEPLOY_FILES)
