"""Guard: every subpackage has an API reference page, in both languages.

The reference is generated by ``mkdocstrings`` from the docstrings already in
the source, which makes it cheap to keep correct and easy to forget entirely: a
new subpackage ships with no page and nothing complains, and a removed one
leaves a page that ``mkdocs build`` renders as an empty stub rather than an
error.

The check runs both ways — a subpackage with no page, and a page with no
subpackage — because only the second is even slightly visible in a build log.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGE = REPO_ROOT / "tempestweb"
REFERENCE = REPO_ROOT / "docs" / "reference"
MKDOCS_YML = REPO_ROOT / "mkdocs.yml"


def _subpackages() -> set[str]:
    """The importable subpackages of ``tempestweb``.

    Returns:
        Directory names holding an ``__init__.py``, excluding caches.
    """
    return {
        child.name
        for child in PACKAGE.iterdir()
        if child.is_dir()
        and (child / "__init__.py").is_file()
        and not child.name.startswith("__")
    }


def _documented() -> set[str]:
    """The subpackages that have a Portuguese reference page.

    Returns:
        The page stems under ``docs/reference/``, ignoring the ``.en`` mirrors.
    """
    return {
        page.stem for page in REFERENCE.glob("*.md") if not page.name.endswith(".en.md")
    }


def test_every_subpackage_has_a_reference_page() -> None:
    """A subpackage with no page is invisible in the published reference.

    Its symbols are then only discoverable by reading the source, which is the
    exact gap the reference exists to close.
    """
    missing = sorted(_subpackages() - _documented())
    assert not missing, "subpackages with no docs/reference page:\n  " + "\n  ".join(
        missing
    )


def test_no_reference_page_without_a_subpackage() -> None:
    """A page for a removed subpackage renders empty instead of failing.

    ``mkdocstrings`` logs nothing useful for an identifier it cannot resolve
    under a non-strict build, so the orphan survives until a reader finds it.
    """
    orphans = sorted(_documented() - _subpackages())
    assert not orphans, (
        "reference pages with no matching subpackage:\n  " + "\n  ".join(orphans)
    )


def test_every_reference_page_is_translated() -> None:
    """Both locales must carry every page, or the English nav has holes."""
    missing = sorted(
        page.name
        for page in REFERENCE.glob("*.md")
        if not page.name.endswith(".en.md")
        and not (REFERENCE / f"{page.stem}.en.md").is_file()
    )
    assert not missing, "reference pages with no .en.md translation:\n  " + "\n  ".join(
        missing
    )


def test_every_reference_page_is_in_the_nav() -> None:
    """A page absent from ``nav:`` is built but unreachable by navigation."""
    config = MKDOCS_YML.read_text(encoding="utf-8")
    absent = sorted(
        stem for stem in _documented() if f"reference/{stem}.md" not in config
    )
    assert not absent, "reference pages missing from mkdocs.yml nav:\n  " + "\n  ".join(
        absent
    )


def test_pages_render_the_mkdocstrings_block() -> None:
    """A page without its ``:::`` block is prose pretending to be a reference.

    Easy to introduce by hand-editing one page and dropping the directive; the
    build still succeeds and the page still looks plausible.
    """
    bare = sorted(
        page.name
        for page in REFERENCE.glob("*.md")
        if f"::: tempestweb.{page.name.removesuffix('.en.md').removesuffix('.md')}"
        not in page.read_text(encoding="utf-8")
    )
    assert not bare, (
        "reference pages with no mkdocstrings directive:\n  " + "\n  ".join(bare)
    )
